// Client-safe UI strings and pantry items (no server imports)

export const UI_STRINGS: Record<string, Record<string, string>> = {
  en: {
    todaysTasks: "Today's Tasks",
    morningTasks: "Morning",
    afternoonTasks: "Afternoon",
    completed: "Completed",
    pending: "Pending",
    tapToComplete: "Tap to complete",
    photoRequired: "Photo required",
    tapToUploadPhoto: "Tap to upload photo",
    instructions: "Instructions",
    newInstruction: "New instruction",
    recipe: "Recipe",
    grocery: "Grocery List",
    pantryCheck: "Pantry Check",
    pantryCheckTitle: "What's left in the pantry?",
    pantryCheckSubtitle: "Please check and tick what you still have",
    otherLeftovers: "Other leftover ingredients (free text)",
    submit: "Submit",
    doYouHave: "Do you have",
    yes: "Yes",
    no: "No",
    employerHasSeen: "Employer has seen this ✓",
    wellDone: "Well done!",
    allDone: "All tasks done for today!",
  },
  id: {
    todaysTasks: "Tugas Hari Ini",
    morningTasks: "Pagi",
    afternoonTasks: "Siang/Sore",
    completed: "Selesai",
    pending: "Belum Selesai",
    tapToComplete: "Ketuk untuk selesai",
    photoRequired: "Foto diperlukan",
    tapToUploadPhoto: "Ketuk untuk unggah foto",
    instructions: "Petunjuk",
    newInstruction: "Petunjuk baru",
    recipe: "Resep",
    grocery: "Daftar Belanja",
    pantryCheck: "Cek Dapur",
    pantryCheckTitle: "Apa yang masih ada di dapur?",
    pantryCheckSubtitle: "Tolong periksa dan centang bahan yang masih ada",
    otherLeftovers: "Bahan sisa lainnya (tulis di sini)",
    submit: "Kirim",
    doYouHave: "Apakah ada",
    yes: "Ada",
    no: "Tidak ada",
    employerHasSeen: "Majikan sudah lihat ✓",
    wellDone: "Bagus sekali!",
    allDone: "Semua tugas hari ini sudah selesai!",
  },
  tl: {
    todaysTasks: "Mga Gawain Ngayon",
    morningTasks: "Umaga",
    afternoonTasks: "Hapon",
    completed: "Tapos Na",
    pending: "Hindi Pa Tapos",
    tapToComplete: "I-tap para tapusin",
    photoRequired: "Kailangan ng litrato",
    tapToUploadPhoto: "I-tap para mag-upload ng litrato",
    instructions: "Mga Tagubilin",
    newInstruction: "Bagong tagubilin",
    recipe: "Resipe",
    grocery: "Listahan ng Pamimili",
    pantryCheck: "Suriin ang Pantry",
    pantryCheckTitle: "Ano ang natira sa pantry?",
    pantryCheckSubtitle: "Pakisuri at markahan ang mga sangkap na mayroon ka pa",
    otherLeftovers: "Ibang natirang sangkap (isulat dito)",
    submit: "Isumite",
    doYouHave: "Mayroon ka ba ng",
    yes: "Mayroon",
    no: "Wala",
    employerHasSeen: "Nakita na ng employer ✓",
    wellDone: "Magaling!",
    allDone: "Lahat ng gawain ngayon ay tapos na!",
  },
  th: {
    todaysTasks: "งานวันนี้",
    morningTasks: "เช้า",
    afternoonTasks: "บ่าย/เย็น",
    completed: "เสร็จแล้ว",
    pending: "ยังไม่เสร็จ",
    tapToComplete: "แตะเพื่อทำเสร็จ",
    photoRequired: "ต้องการรูปภาพ",
    tapToUploadPhoto: "แตะเพื่ออัปโหลดรูปภาพ",
    instructions: "คำแนะนำ",
    newInstruction: "คำแนะนำใหม่",
    recipe: "สูตรอาหาร",
    grocery: "รายการของชำ",
    pantryCheck: "ตรวจสอบครัว",
    pantryCheckTitle: "มีอะไรเหลือในครัวบ้าง?",
    pantryCheckSubtitle: "กรุณาตรวจสอบและทำเครื่องหมายสิ่งที่ยังมีอยู่",
    otherLeftovers: "วัตถุดิบที่เหลืออื่นๆ (เขียนที่นี่)",
    submit: "ส่ง",
    doYouHave: "มี",
    yes: "มี",
    no: "ไม่มี",
    employerHasSeen: "นายจ้างเห็นแล้ว ✓",
    wellDone: "เยี่ยมมาก!",
    allDone: "งานทั้งหมดวันนี้เสร็จแล้ว!",
  },
  my: {
    todaysTasks: "ဒီနေ့လုပ်ရမည့်အလုပ်များ",
    morningTasks: "နံနက်",
    afternoonTasks: "နေ့လယ်/ညနေ",
    completed: "ပြီးဆုံးပြီ",
    pending: "မပြီးသေး",
    tapToComplete: "ပြီးဆုံးရန် နှိပ်ပါ",
    photoRequired: "ဓာတ်ပုံလိုအပ်သည်",
    tapToUploadPhoto: "ဓာတ်ပုံတင်ရန် နှိပ်ပါ",
    instructions: "ညွှန်ကြားချက်များ",
    newInstruction: "ညွှန်ကြားချက်အသစ်",
    recipe: "ချက်ပြုတ်နည်း",
    grocery: "စျေးဝယ်စာရင်း",
    pantryCheck: "ဟင်းချောင်စစ်ဆေးမှု",
    pantryCheckTitle: "ဟင်းချောင်မှာ ဘာကျန်သေးလဲ?",
    pantryCheckSubtitle: "ကျေးဇူးပြု၍ စစ်ဆေးပြီး ရှိသောပစ္စည်းများကို မှတ်သားပါ",
    otherLeftovers: "ကျန်ရှိသောပစ္စည်းများ (ဤနေရာတွင် ရေးပါ)",
    submit: "တင်သွင်းပါ",
    doYouHave: "ရှိပါသလား",
    yes: "ရှိသည်",
    no: "မရှိ",
    employerHasSeen: "အလုပ်ရှင် မြင်ပြီးပြီ ✓",
    wellDone: "ကောင်းမွန်ပါသည်!",
    allDone: "ယနေ့အလုပ်များ အားလုံးပြီးဆုံးပြီ!",
  },
};

export function getUIString(key: string, language: string): string {
  const langStrings = UI_STRINGS[language] || UI_STRINGS.id;
  return langStrings[key] || UI_STRINGS.en[key] || key;
}

export const DEFAULT_PANTRY_ITEMS = [
  "Oyster sauce",
  "Soy sauce",
  "Fish sauce",
  "Sesame oil",
  "Dark soy sauce",
  "Cooking wine",
  "Cornstarch",
  "White pepper",
  "Black pepper",
  "Salt",
  "Sugar",
  "Garlic",
  "Ginger",
  "Vegetable oil",
  "Chicken stock / cubes",
  "Dried chilli",
  "Pasta (dried)",
  "Rice",
  "Noodles (dried)",
  "Canned tomatoes",
  "Canned coconut milk",
  "Curry powder",
  "Cumin",
  "Paprika",
  "Turmeric",
  "Olive oil",
  "Butter",
  "Plain flour",
  "Bread crumbs / panko",
  "Sriracha sauce",
  "Mayonnaise",
  "Tomato paste",
];
